services:
  
  topsis-web:
    build:
      dockerfile: "Dockerfile"
    hostname: www1
    ports:
      - "8080:8080"
    depends_on:
      - topsis-postgres
    networks:
      - backend
    volumes:
       - ./.secrets:/recaptcha_creds
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DatabaseSettings__Server: db1
      GOOGLE_APPLICATION_CREDENTIALS: /recaptcha_creds/recaptcha_creds.json

  topsis-postgres:
    container_name: postgres_container
    image: postgres
    hostname: db1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
       - ./Docker/data/postgres:/data/postgres
    logging:
      options:
        tag: "{{.DaemonName}}(image={{.ImageName}};name={{.Name}};id={{.ID}})"
    ports:
      - "5432:5432"
    networks:
      - backend
    restart: unless-stopped


networks:       
  backend:
    driver: bridge