// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Topsis.Adapters.Database;

namespace Topsis.Adapters.Database.Migrations
{
    [DbContext(typeof(WorkspaceDbContext))]
    [Migration("20211013074359_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "4E59CEA1-FC55-49F5-BF30-4BC46A0DDA70",
                            RoleId = "4E59CEA1-FC55-49F5-BF30-4BC46A0DDA7A"
                        },
                        new
                        {
                            UserId = "4E59CEA1-FC55-49F5-BF30-4BC46A0DDA70",
                            RoleId = "4E59CEA1-FC55-49F5-BF30-4BC46A0DDA7B"
                        },
                        new
                        {
                            UserId = "4E59CEA1-FC55-49F5-BF30-4BC46A0DDA70",
                            RoleId = "4E59CEA1-FC55-49F5-BF30-4BC46A0DDA7C"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("Value")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Topsis.Application.Contracts.Identity.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "4E59CEA1-FC55-49F5-BF30-4BC46A0DDA7A",
                            ConcurrencyStamp = "d88c0309-8220-4b8b-bed8-c3fad4f31032",
                            Name = "admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "4E59CEA1-FC55-49F5-BF30-4BC46A0DDA7B",
                            ConcurrencyStamp = "81af51b3-0585-4657-9970-c787e11eb5c1",
                            Name = "moderator",
                            NormalizedName = "MODERATOR"
                        },
                        new
                        {
                            Id = "4E59CEA1-FC55-49F5-BF30-4BC46A0DDA7C",
                            ConcurrencyStamp = "2ee994ab-f1bb-4bce-8851-7818defdda9b",
                            Name = "stakeholder",
                            NormalizedName = "STAKEHOLDER"
                        });
                });

            modelBuilder.Entity("Topsis.Application.Contracts.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("CountryId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FirstName")
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.Property<int?>("JobCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("JobCategoryId");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "4E59CEA1-FC55-49F5-BF30-4BC46A0DDA70",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5a707ad6-bd1c-4706-8323-bef16250ed1a",
                            Email = "a.soursos@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "a.soursos@gmail.com",
                            NormalizedUserName = "a.soursos@gmail.com",
                            PasswordHash = "AQAAAAEAACcQAAAAEMMXtIDR5MY0QGKhlh5KxqWZ6YC1KkCnsh3ILk2xoKd6eKhbDB/T61n9kEoV7RRbIQ==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "7f0086e4-7718-491c-8627-18cdc291d491",
                            TwoFactorEnabled = false,
                            UserName = "a.soursos@gmail.com"
                        });
                });

            modelBuilder.Entity("Topsis.Domain.Alternative", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<short>("Order")
                        .HasColumnType("smallint");

                    b.Property<int?>("QuestionnaireId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("QuestionnaireId");

                    b.ToTable("WsAlternatives");
                });

            modelBuilder.Entity("Topsis.Domain.Country", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("A2Code")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("A3Code")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Title")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("WsCountries");

                    b.HasData(
                        new
                        {
                            Id = "004",
                            A2Code = "AF",
                            A3Code = "AFG",
                            Title = "Afghanistan"
                        },
                        new
                        {
                            Id = "008",
                            A2Code = "AL",
                            A3Code = "ALB",
                            Title = "Albania"
                        },
                        new
                        {
                            Id = "012",
                            A2Code = "DZ",
                            A3Code = "DZA",
                            Title = "Algeria"
                        },
                        new
                        {
                            Id = "016",
                            A2Code = "AS",
                            A3Code = "ASM",
                            Title = "American Samoa"
                        },
                        new
                        {
                            Id = "020",
                            A2Code = "AD",
                            A3Code = "AND",
                            Title = "Andorra"
                        },
                        new
                        {
                            Id = "024",
                            A2Code = "AO",
                            A3Code = "AGO",
                            Title = "Angola"
                        },
                        new
                        {
                            Id = "660",
                            A2Code = "AI",
                            A3Code = "AIA",
                            Title = "Anguilla"
                        },
                        new
                        {
                            Id = "010",
                            A2Code = "AQ",
                            A3Code = "ATA",
                            Title = "Antarctica"
                        },
                        new
                        {
                            Id = "028",
                            A2Code = "AG",
                            A3Code = "ATG",
                            Title = "Antigua and Barbuda"
                        },
                        new
                        {
                            Id = "032",
                            A2Code = "AR",
                            A3Code = "ARG",
                            Title = "Argentina"
                        },
                        new
                        {
                            Id = "051",
                            A2Code = "AM",
                            A3Code = "ARM",
                            Title = "Armenia"
                        },
                        new
                        {
                            Id = "533",
                            A2Code = "AW",
                            A3Code = "ABW",
                            Title = "Aruba"
                        },
                        new
                        {
                            Id = "036",
                            A2Code = "AU",
                            A3Code = "AUS",
                            Title = "Australia"
                        },
                        new
                        {
                            Id = "040",
                            A2Code = "AT",
                            A3Code = "AUT",
                            Title = "Austria"
                        },
                        new
                        {
                            Id = "031",
                            A2Code = "AZ",
                            A3Code = "AZE",
                            Title = "Azerbaijan"
                        },
                        new
                        {
                            Id = "044",
                            A2Code = "BS",
                            A3Code = "BHS",
                            Title = "Bahamas (the)"
                        },
                        new
                        {
                            Id = "048",
                            A2Code = "BH",
                            A3Code = "BHR",
                            Title = "Bahrain"
                        },
                        new
                        {
                            Id = "050",
                            A2Code = "BD",
                            A3Code = "BGD",
                            Title = "Bangladesh"
                        },
                        new
                        {
                            Id = "052",
                            A2Code = "BB",
                            A3Code = "BRB",
                            Title = "Barbados"
                        },
                        new
                        {
                            Id = "112",
                            A2Code = "BY",
                            A3Code = "BLR",
                            Title = "Belarus"
                        },
                        new
                        {
                            Id = "056",
                            A2Code = "BE",
                            A3Code = "BEL",
                            Title = "Belgium"
                        },
                        new
                        {
                            Id = "084",
                            A2Code = "BZ",
                            A3Code = "BLZ",
                            Title = "Belize"
                        },
                        new
                        {
                            Id = "204",
                            A2Code = "BJ",
                            A3Code = "BEN",
                            Title = "Benin"
                        },
                        new
                        {
                            Id = "060",
                            A2Code = "BM",
                            A3Code = "BMU",
                            Title = "Bermuda"
                        },
                        new
                        {
                            Id = "064",
                            A2Code = "BT",
                            A3Code = "BTN",
                            Title = "Bhutan"
                        },
                        new
                        {
                            Id = "068",
                            A2Code = "BO",
                            A3Code = "BOL",
                            Title = "Bolivia (Plurinational State of)"
                        },
                        new
                        {
                            Id = "535",
                            A2Code = "BQ",
                            A3Code = "BES",
                            Title = "Bonaire, Sint Eustatius and Saba"
                        },
                        new
                        {
                            Id = "070",
                            A2Code = "BA",
                            A3Code = "BIH",
                            Title = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            Id = "072",
                            A2Code = "BW",
                            A3Code = "BWA",
                            Title = "Botswana"
                        },
                        new
                        {
                            Id = "074",
                            A2Code = "BV",
                            A3Code = "BVT",
                            Title = "Bouvet Island"
                        },
                        new
                        {
                            Id = "076",
                            A2Code = "BR",
                            A3Code = "BRA",
                            Title = "Brazil"
                        },
                        new
                        {
                            Id = "086",
                            A2Code = "IO",
                            A3Code = "IOT",
                            Title = "British Indian Ocean Territory (the)"
                        },
                        new
                        {
                            Id = "096",
                            A2Code = "BN",
                            A3Code = "BRN",
                            Title = "Brunei Darussalam"
                        },
                        new
                        {
                            Id = "100",
                            A2Code = "BG",
                            A3Code = "BGR",
                            Title = "Bulgaria"
                        },
                        new
                        {
                            Id = "854",
                            A2Code = "BF",
                            A3Code = "BFA",
                            Title = "Burkina Faso"
                        },
                        new
                        {
                            Id = "108",
                            A2Code = "BI",
                            A3Code = "BDI",
                            Title = "Burundi"
                        },
                        new
                        {
                            Id = "132",
                            A2Code = "CV",
                            A3Code = "CPV",
                            Title = "Cabo Verde"
                        },
                        new
                        {
                            Id = "116",
                            A2Code = "KH",
                            A3Code = "KHM",
                            Title = "Cambodia"
                        },
                        new
                        {
                            Id = "120",
                            A2Code = "CM",
                            A3Code = "CMR",
                            Title = "Cameroon"
                        },
                        new
                        {
                            Id = "124",
                            A2Code = "CA",
                            A3Code = "CAN",
                            Title = "Canada"
                        },
                        new
                        {
                            Id = "136",
                            A2Code = "KY",
                            A3Code = "CYM",
                            Title = "Cayman Islands (the)"
                        },
                        new
                        {
                            Id = "140",
                            A2Code = "CF",
                            A3Code = "CAF",
                            Title = "Central African Republic (the)"
                        },
                        new
                        {
                            Id = "148",
                            A2Code = "TD",
                            A3Code = "TCD",
                            Title = "Chad"
                        },
                        new
                        {
                            Id = "152",
                            A2Code = "CL",
                            A3Code = "CHL",
                            Title = "Chile"
                        },
                        new
                        {
                            Id = "156",
                            A2Code = "CN",
                            A3Code = "CHN",
                            Title = "China"
                        },
                        new
                        {
                            Id = "162",
                            A2Code = "CX",
                            A3Code = "CXR",
                            Title = "Christmas Island"
                        },
                        new
                        {
                            Id = "166",
                            A2Code = "CC",
                            A3Code = "CCK",
                            Title = "Cocos (Keeling) Islands (the)"
                        },
                        new
                        {
                            Id = "170",
                            A2Code = "CO",
                            A3Code = "COL",
                            Title = "Colombia"
                        },
                        new
                        {
                            Id = "174",
                            A2Code = "KM",
                            A3Code = "COM",
                            Title = "Comoros (the)"
                        },
                        new
                        {
                            Id = "180",
                            A2Code = "CD",
                            A3Code = "COD",
                            Title = "Congo (the Democratic Republic of the)"
                        },
                        new
                        {
                            Id = "178",
                            A2Code = "CG",
                            A3Code = "COG",
                            Title = "Congo (the)"
                        },
                        new
                        {
                            Id = "184",
                            A2Code = "CK",
                            A3Code = "COK",
                            Title = "Cook Islands (the)"
                        },
                        new
                        {
                            Id = "188",
                            A2Code = "CR",
                            A3Code = "CRI",
                            Title = "Costa Rica"
                        },
                        new
                        {
                            Id = "191",
                            A2Code = "HR",
                            A3Code = "HRV",
                            Title = "Croatia"
                        },
                        new
                        {
                            Id = "192",
                            A2Code = "CU",
                            A3Code = "CUB",
                            Title = "Cuba"
                        },
                        new
                        {
                            Id = "531",
                            A2Code = "CW",
                            A3Code = "CUW",
                            Title = "Curaçao"
                        },
                        new
                        {
                            Id = "196",
                            A2Code = "CY",
                            A3Code = "CYP",
                            Title = "Cyprus"
                        },
                        new
                        {
                            Id = "203",
                            A2Code = "CZ",
                            A3Code = "CZE",
                            Title = "Czechia"
                        },
                        new
                        {
                            Id = "384",
                            A2Code = "CI",
                            A3Code = "CIV",
                            Title = "Côte d'Ivoire"
                        },
                        new
                        {
                            Id = "208",
                            A2Code = "DK",
                            A3Code = "DNK",
                            Title = "Denmark"
                        },
                        new
                        {
                            Id = "262",
                            A2Code = "DJ",
                            A3Code = "DJI",
                            Title = "Djibouti"
                        },
                        new
                        {
                            Id = "212",
                            A2Code = "DM",
                            A3Code = "DMA",
                            Title = "Dominica"
                        },
                        new
                        {
                            Id = "214",
                            A2Code = "DO",
                            A3Code = "DOM",
                            Title = "Dominican Republic (the)"
                        },
                        new
                        {
                            Id = "218",
                            A2Code = "EC",
                            A3Code = "ECU",
                            Title = "Ecuador"
                        },
                        new
                        {
                            Id = "818",
                            A2Code = "EG",
                            A3Code = "EGY",
                            Title = "Egypt"
                        },
                        new
                        {
                            Id = "222",
                            A2Code = "SV",
                            A3Code = "SLV",
                            Title = "El Salvador"
                        },
                        new
                        {
                            Id = "226",
                            A2Code = "GQ",
                            A3Code = "GNQ",
                            Title = "Equatorial Guinea"
                        },
                        new
                        {
                            Id = "232",
                            A2Code = "ER",
                            A3Code = "ERI",
                            Title = "Eritrea"
                        },
                        new
                        {
                            Id = "233",
                            A2Code = "EE",
                            A3Code = "EST",
                            Title = "Estonia"
                        },
                        new
                        {
                            Id = "748",
                            A2Code = "SZ",
                            A3Code = "SWZ",
                            Title = "Eswatini"
                        },
                        new
                        {
                            Id = "231",
                            A2Code = "ET",
                            A3Code = "ETH",
                            Title = "Ethiopia"
                        },
                        new
                        {
                            Id = "238",
                            A2Code = "FK",
                            A3Code = "FLK",
                            Title = "Falkland Islands (the) [Malvinas]"
                        },
                        new
                        {
                            Id = "234",
                            A2Code = "FO",
                            A3Code = "FRO",
                            Title = "Faroe Islands (the)"
                        },
                        new
                        {
                            Id = "242",
                            A2Code = "FJ",
                            A3Code = "FJI",
                            Title = "Fiji"
                        },
                        new
                        {
                            Id = "246",
                            A2Code = "FI",
                            A3Code = "FIN",
                            Title = "Finland"
                        },
                        new
                        {
                            Id = "250",
                            A2Code = "FR",
                            A3Code = "FRA",
                            Title = "France"
                        },
                        new
                        {
                            Id = "254",
                            A2Code = "GF",
                            A3Code = "GUF",
                            Title = "French Guiana"
                        },
                        new
                        {
                            Id = "258",
                            A2Code = "PF",
                            A3Code = "PYF",
                            Title = "French Polynesia"
                        },
                        new
                        {
                            Id = "260",
                            A2Code = "TF",
                            A3Code = "ATF",
                            Title = "French Southern Territories (the)"
                        },
                        new
                        {
                            Id = "266",
                            A2Code = "GA",
                            A3Code = "GAB",
                            Title = "Gabon"
                        },
                        new
                        {
                            Id = "270",
                            A2Code = "GM",
                            A3Code = "GMB",
                            Title = "Gambia (the)"
                        },
                        new
                        {
                            Id = "268",
                            A2Code = "GE",
                            A3Code = "GEO",
                            Title = "Georgia"
                        },
                        new
                        {
                            Id = "276",
                            A2Code = "DE",
                            A3Code = "DEU",
                            Title = "Germany"
                        },
                        new
                        {
                            Id = "288",
                            A2Code = "GH",
                            A3Code = "GHA",
                            Title = "Ghana"
                        },
                        new
                        {
                            Id = "292",
                            A2Code = "GI",
                            A3Code = "GIB",
                            Title = "Gibraltar"
                        },
                        new
                        {
                            Id = "300",
                            A2Code = "GR",
                            A3Code = "GRC",
                            Title = "Greece"
                        },
                        new
                        {
                            Id = "304",
                            A2Code = "GL",
                            A3Code = "GRL",
                            Title = "Greenland"
                        },
                        new
                        {
                            Id = "308",
                            A2Code = "GD",
                            A3Code = "GRD",
                            Title = "Grenada"
                        },
                        new
                        {
                            Id = "312",
                            A2Code = "GP",
                            A3Code = "GLP",
                            Title = "Guadeloupe"
                        },
                        new
                        {
                            Id = "316",
                            A2Code = "GU",
                            A3Code = "GUM",
                            Title = "Guam"
                        },
                        new
                        {
                            Id = "320",
                            A2Code = "GT",
                            A3Code = "GTM",
                            Title = "Guatemala"
                        },
                        new
                        {
                            Id = "831",
                            A2Code = "GG",
                            A3Code = "GGY",
                            Title = "Guernsey"
                        },
                        new
                        {
                            Id = "324",
                            A2Code = "GN",
                            A3Code = "GIN",
                            Title = "Guinea"
                        },
                        new
                        {
                            Id = "624",
                            A2Code = "GW",
                            A3Code = "GNB",
                            Title = "Guinea-Bissau"
                        },
                        new
                        {
                            Id = "328",
                            A2Code = "GY",
                            A3Code = "GUY",
                            Title = "Guyana"
                        },
                        new
                        {
                            Id = "332",
                            A2Code = "HT",
                            A3Code = "HTI",
                            Title = "Haiti"
                        },
                        new
                        {
                            Id = "334",
                            A2Code = "HM",
                            A3Code = "HMD",
                            Title = "Heard Island and McDonald Islands"
                        },
                        new
                        {
                            Id = "336",
                            A2Code = "VA",
                            A3Code = "VAT",
                            Title = "Holy See (the)"
                        },
                        new
                        {
                            Id = "340",
                            A2Code = "HN",
                            A3Code = "HND",
                            Title = "Honduras"
                        },
                        new
                        {
                            Id = "344",
                            A2Code = "HK",
                            A3Code = "HKG",
                            Title = "Hong Kong"
                        },
                        new
                        {
                            Id = "348",
                            A2Code = "HU",
                            A3Code = "HUN",
                            Title = "Hungary"
                        },
                        new
                        {
                            Id = "352",
                            A2Code = "IS",
                            A3Code = "ISL",
                            Title = "Iceland"
                        },
                        new
                        {
                            Id = "356",
                            A2Code = "IN",
                            A3Code = "IND",
                            Title = "India"
                        },
                        new
                        {
                            Id = "360",
                            A2Code = "ID",
                            A3Code = "IDN",
                            Title = "Indonesia"
                        },
                        new
                        {
                            Id = "364",
                            A2Code = "IR",
                            A3Code = "IRN",
                            Title = "Iran (Islamic Republic of)"
                        },
                        new
                        {
                            Id = "368",
                            A2Code = "IQ",
                            A3Code = "IRQ",
                            Title = "Iraq"
                        },
                        new
                        {
                            Id = "372",
                            A2Code = "IE",
                            A3Code = "IRL",
                            Title = "Ireland"
                        },
                        new
                        {
                            Id = "833",
                            A2Code = "IM",
                            A3Code = "IMN",
                            Title = "Isle of Man"
                        },
                        new
                        {
                            Id = "376",
                            A2Code = "IL",
                            A3Code = "ISR",
                            Title = "Israel"
                        },
                        new
                        {
                            Id = "380",
                            A2Code = "IT",
                            A3Code = "ITA",
                            Title = "Italy"
                        },
                        new
                        {
                            Id = "388",
                            A2Code = "JM",
                            A3Code = "JAM",
                            Title = "Jamaica"
                        },
                        new
                        {
                            Id = "392",
                            A2Code = "JP",
                            A3Code = "JPN",
                            Title = "Japan"
                        },
                        new
                        {
                            Id = "832",
                            A2Code = "JE",
                            A3Code = "JEY",
                            Title = "Jersey"
                        },
                        new
                        {
                            Id = "400",
                            A2Code = "JO",
                            A3Code = "JOR",
                            Title = "Jordan"
                        },
                        new
                        {
                            Id = "398",
                            A2Code = "KZ",
                            A3Code = "KAZ",
                            Title = "Kazakhstan"
                        },
                        new
                        {
                            Id = "404",
                            A2Code = "KE",
                            A3Code = "KEN",
                            Title = "Kenya"
                        },
                        new
                        {
                            Id = "296",
                            A2Code = "KI",
                            A3Code = "KIR",
                            Title = "Kiribati"
                        },
                        new
                        {
                            Id = "408",
                            A2Code = "KP",
                            A3Code = "PRK",
                            Title = "Korea (the Democratic People's Republic of)"
                        },
                        new
                        {
                            Id = "410",
                            A2Code = "KR",
                            A3Code = "KOR",
                            Title = "Korea (the Republic of)"
                        },
                        new
                        {
                            Id = "414",
                            A2Code = "KW",
                            A3Code = "KWT",
                            Title = "Kuwait"
                        },
                        new
                        {
                            Id = "417",
                            A2Code = "KG",
                            A3Code = "KGZ",
                            Title = "Kyrgyzstan"
                        },
                        new
                        {
                            Id = "418",
                            A2Code = "LA",
                            A3Code = "LAO",
                            Title = "Lao People's Democratic Republic (the)"
                        },
                        new
                        {
                            Id = "428",
                            A2Code = "LV",
                            A3Code = "LVA",
                            Title = "Latvia"
                        },
                        new
                        {
                            Id = "422",
                            A2Code = "LB",
                            A3Code = "LBN",
                            Title = "Lebanon"
                        },
                        new
                        {
                            Id = "426",
                            A2Code = "LS",
                            A3Code = "LSO",
                            Title = "Lesotho"
                        },
                        new
                        {
                            Id = "430",
                            A2Code = "LR",
                            A3Code = "LBR",
                            Title = "Liberia"
                        },
                        new
                        {
                            Id = "434",
                            A2Code = "LY",
                            A3Code = "LBY",
                            Title = "Libya"
                        },
                        new
                        {
                            Id = "438",
                            A2Code = "LI",
                            A3Code = "LIE",
                            Title = "Liechtenstein"
                        },
                        new
                        {
                            Id = "440",
                            A2Code = "LT",
                            A3Code = "LTU",
                            Title = "Lithuania"
                        },
                        new
                        {
                            Id = "442",
                            A2Code = "LU",
                            A3Code = "LUX",
                            Title = "Luxembourg"
                        },
                        new
                        {
                            Id = "446",
                            A2Code = "MO",
                            A3Code = "MAC",
                            Title = "Macao"
                        },
                        new
                        {
                            Id = "450",
                            A2Code = "MG",
                            A3Code = "MDG",
                            Title = "Madagascar"
                        },
                        new
                        {
                            Id = "454",
                            A2Code = "MW",
                            A3Code = "MWI",
                            Title = "Malawi"
                        },
                        new
                        {
                            Id = "458",
                            A2Code = "MY",
                            A3Code = "MYS",
                            Title = "Malaysia"
                        },
                        new
                        {
                            Id = "462",
                            A2Code = "MV",
                            A3Code = "MDV",
                            Title = "Maldives"
                        },
                        new
                        {
                            Id = "466",
                            A2Code = "ML",
                            A3Code = "MLI",
                            Title = "Mali"
                        },
                        new
                        {
                            Id = "470",
                            A2Code = "MT",
                            A3Code = "MLT",
                            Title = "Malta"
                        },
                        new
                        {
                            Id = "584",
                            A2Code = "MH",
                            A3Code = "MHL",
                            Title = "Marshall Islands (the)"
                        },
                        new
                        {
                            Id = "474",
                            A2Code = "MQ",
                            A3Code = "MTQ",
                            Title = "Martinique"
                        },
                        new
                        {
                            Id = "478",
                            A2Code = "MR",
                            A3Code = "MRT",
                            Title = "Mauritania"
                        },
                        new
                        {
                            Id = "480",
                            A2Code = "MU",
                            A3Code = "MUS",
                            Title = "Mauritius"
                        },
                        new
                        {
                            Id = "175",
                            A2Code = "YT",
                            A3Code = "MYT",
                            Title = "Mayotte"
                        },
                        new
                        {
                            Id = "484",
                            A2Code = "MX",
                            A3Code = "MEX",
                            Title = "Mexico"
                        },
                        new
                        {
                            Id = "583",
                            A2Code = "FM",
                            A3Code = "FSM",
                            Title = "Micronesia (Federated States of)"
                        },
                        new
                        {
                            Id = "498",
                            A2Code = "MD",
                            A3Code = "MDA",
                            Title = "Moldova (the Republic of)"
                        },
                        new
                        {
                            Id = "492",
                            A2Code = "MC",
                            A3Code = "MCO",
                            Title = "Monaco"
                        },
                        new
                        {
                            Id = "496",
                            A2Code = "MN",
                            A3Code = "MNG",
                            Title = "Mongolia"
                        },
                        new
                        {
                            Id = "499",
                            A2Code = "ME",
                            A3Code = "MNE",
                            Title = "Montenegro"
                        },
                        new
                        {
                            Id = "500",
                            A2Code = "MS",
                            A3Code = "MSR",
                            Title = "Montserrat"
                        },
                        new
                        {
                            Id = "504",
                            A2Code = "MA",
                            A3Code = "MAR",
                            Title = "Morocco"
                        },
                        new
                        {
                            Id = "508",
                            A2Code = "MZ",
                            A3Code = "MOZ",
                            Title = "Mozambique"
                        },
                        new
                        {
                            Id = "104",
                            A2Code = "MM",
                            A3Code = "MMR",
                            Title = "Myanmar"
                        },
                        new
                        {
                            Id = "516",
                            A2Code = "NA",
                            A3Code = "NAM",
                            Title = "Namibia"
                        },
                        new
                        {
                            Id = "520",
                            A2Code = "NR",
                            A3Code = "NRU",
                            Title = "Nauru"
                        },
                        new
                        {
                            Id = "524",
                            A2Code = "NP",
                            A3Code = "NPL",
                            Title = "Nepal"
                        },
                        new
                        {
                            Id = "528",
                            A2Code = "NL",
                            A3Code = "NLD",
                            Title = "Netherlands (the)"
                        },
                        new
                        {
                            Id = "540",
                            A2Code = "NC",
                            A3Code = "NCL",
                            Title = "New Caledonia"
                        },
                        new
                        {
                            Id = "554",
                            A2Code = "NZ",
                            A3Code = "NZL",
                            Title = "New Zealand"
                        },
                        new
                        {
                            Id = "558",
                            A2Code = "NI",
                            A3Code = "NIC",
                            Title = "Nicaragua"
                        },
                        new
                        {
                            Id = "562",
                            A2Code = "NE",
                            A3Code = "NER",
                            Title = "Niger (the)"
                        },
                        new
                        {
                            Id = "566",
                            A2Code = "NG",
                            A3Code = "NGA",
                            Title = "Nigeria"
                        },
                        new
                        {
                            Id = "570",
                            A2Code = "NU",
                            A3Code = "NIU",
                            Title = "Niue"
                        },
                        new
                        {
                            Id = "574",
                            A2Code = "NF",
                            A3Code = "NFK",
                            Title = "Norfolk Island"
                        },
                        new
                        {
                            Id = "580",
                            A2Code = "MP",
                            A3Code = "MNP",
                            Title = "Northern Mariana Islands (the)"
                        },
                        new
                        {
                            Id = "578",
                            A2Code = "NO",
                            A3Code = "NOR",
                            Title = "Norway"
                        },
                        new
                        {
                            Id = "512",
                            A2Code = "OM",
                            A3Code = "OMN",
                            Title = "Oman"
                        },
                        new
                        {
                            Id = "586",
                            A2Code = "PK",
                            A3Code = "PAK",
                            Title = "Pakistan"
                        },
                        new
                        {
                            Id = "585",
                            A2Code = "PW",
                            A3Code = "PLW",
                            Title = "Palau"
                        },
                        new
                        {
                            Id = "275",
                            A2Code = "PS",
                            A3Code = "PSE",
                            Title = "Palestine, State of"
                        },
                        new
                        {
                            Id = "591",
                            A2Code = "PA",
                            A3Code = "PAN",
                            Title = "Panama"
                        },
                        new
                        {
                            Id = "598",
                            A2Code = "PG",
                            A3Code = "PNG",
                            Title = "Papua New Guinea"
                        },
                        new
                        {
                            Id = "600",
                            A2Code = "PY",
                            A3Code = "PRY",
                            Title = "Paraguay"
                        },
                        new
                        {
                            Id = "604",
                            A2Code = "PE",
                            A3Code = "PER",
                            Title = "Peru"
                        },
                        new
                        {
                            Id = "608",
                            A2Code = "PH",
                            A3Code = "PHL",
                            Title = "Philippines (the)"
                        },
                        new
                        {
                            Id = "612",
                            A2Code = "PN",
                            A3Code = "PCN",
                            Title = "Pitcairn"
                        },
                        new
                        {
                            Id = "616",
                            A2Code = "PL",
                            A3Code = "POL",
                            Title = "Poland"
                        },
                        new
                        {
                            Id = "620",
                            A2Code = "PT",
                            A3Code = "PRT",
                            Title = "Portugal"
                        },
                        new
                        {
                            Id = "630",
                            A2Code = "PR",
                            A3Code = "PRI",
                            Title = "Puerto Rico"
                        },
                        new
                        {
                            Id = "634",
                            A2Code = "QA",
                            A3Code = "QAT",
                            Title = "Qatar"
                        },
                        new
                        {
                            Id = "807",
                            A2Code = "MK",
                            A3Code = "MKD",
                            Title = "Republic of North Macedonia"
                        },
                        new
                        {
                            Id = "642",
                            A2Code = "RO",
                            A3Code = "ROU",
                            Title = "Romania"
                        },
                        new
                        {
                            Id = "643",
                            A2Code = "RU",
                            A3Code = "RUS",
                            Title = "Russian Federation (the)"
                        },
                        new
                        {
                            Id = "646",
                            A2Code = "RW",
                            A3Code = "RWA",
                            Title = "Rwanda"
                        },
                        new
                        {
                            Id = "638",
                            A2Code = "RE",
                            A3Code = "REU",
                            Title = "Réunion"
                        },
                        new
                        {
                            Id = "652",
                            A2Code = "BL",
                            A3Code = "BLM",
                            Title = "Saint Barthélemy"
                        },
                        new
                        {
                            Id = "654",
                            A2Code = "SH",
                            A3Code = "SHN",
                            Title = "Saint Helena, Ascension and Tristan da Cunha"
                        },
                        new
                        {
                            Id = "659",
                            A2Code = "KN",
                            A3Code = "KNA",
                            Title = "Saint Kitts and Nevis"
                        },
                        new
                        {
                            Id = "662",
                            A2Code = "LC",
                            A3Code = "LCA",
                            Title = "Saint Lucia"
                        },
                        new
                        {
                            Id = "663",
                            A2Code = "MF",
                            A3Code = "MAF",
                            Title = "Saint Martin (French part)"
                        },
                        new
                        {
                            Id = "666",
                            A2Code = "PM",
                            A3Code = "SPM",
                            Title = "Saint Pierre and Miquelon"
                        },
                        new
                        {
                            Id = "670",
                            A2Code = "VC",
                            A3Code = "VCT",
                            Title = "Saint Vincent and the Grenadines"
                        },
                        new
                        {
                            Id = "882",
                            A2Code = "WS",
                            A3Code = "WSM",
                            Title = "Samoa"
                        },
                        new
                        {
                            Id = "674",
                            A2Code = "SM",
                            A3Code = "SMR",
                            Title = "San Marino"
                        },
                        new
                        {
                            Id = "678",
                            A2Code = "ST",
                            A3Code = "STP",
                            Title = "Sao Tome and Principe"
                        },
                        new
                        {
                            Id = "682",
                            A2Code = "SA",
                            A3Code = "SAU",
                            Title = "Saudi Arabia"
                        },
                        new
                        {
                            Id = "686",
                            A2Code = "SN",
                            A3Code = "SEN",
                            Title = "Senegal"
                        },
                        new
                        {
                            Id = "688",
                            A2Code = "RS",
                            A3Code = "SRB",
                            Title = "Serbia"
                        },
                        new
                        {
                            Id = "690",
                            A2Code = "SC",
                            A3Code = "SYC",
                            Title = "Seychelles"
                        },
                        new
                        {
                            Id = "694",
                            A2Code = "SL",
                            A3Code = "SLE",
                            Title = "Sierra Leone"
                        },
                        new
                        {
                            Id = "702",
                            A2Code = "SG",
                            A3Code = "SGP",
                            Title = "Singapore"
                        },
                        new
                        {
                            Id = "534",
                            A2Code = "SX",
                            A3Code = "SXM",
                            Title = "Sint Maarten (Dutch part)"
                        },
                        new
                        {
                            Id = "703",
                            A2Code = "SK",
                            A3Code = "SVK",
                            Title = "Slovakia"
                        },
                        new
                        {
                            Id = "705",
                            A2Code = "SI",
                            A3Code = "SVN",
                            Title = "Slovenia"
                        },
                        new
                        {
                            Id = "090",
                            A2Code = "SB",
                            A3Code = "SLB",
                            Title = "Solomon Islands"
                        },
                        new
                        {
                            Id = "706",
                            A2Code = "SO",
                            A3Code = "SOM",
                            Title = "Somalia"
                        },
                        new
                        {
                            Id = "710",
                            A2Code = "ZA",
                            A3Code = "ZAF",
                            Title = "South Africa"
                        },
                        new
                        {
                            Id = "239",
                            A2Code = "GS",
                            A3Code = "SGS",
                            Title = "South Georgia and the South Sandwich Islands"
                        },
                        new
                        {
                            Id = "728",
                            A2Code = "SS",
                            A3Code = "SSD",
                            Title = "South Sudan"
                        },
                        new
                        {
                            Id = "724",
                            A2Code = "ES",
                            A3Code = "ESP",
                            Title = "Spain"
                        },
                        new
                        {
                            Id = "144",
                            A2Code = "LK",
                            A3Code = "LKA",
                            Title = "Sri Lanka"
                        },
                        new
                        {
                            Id = "729",
                            A2Code = "SD",
                            A3Code = "SDN",
                            Title = "Sudan (the)"
                        },
                        new
                        {
                            Id = "740",
                            A2Code = "SR",
                            A3Code = "SUR",
                            Title = "Suriname"
                        },
                        new
                        {
                            Id = "744",
                            A2Code = "SJ",
                            A3Code = "SJM",
                            Title = "Svalbard and Jan Mayen"
                        },
                        new
                        {
                            Id = "752",
                            A2Code = "SE",
                            A3Code = "SWE",
                            Title = "Sweden"
                        },
                        new
                        {
                            Id = "756",
                            A2Code = "CH",
                            A3Code = "CHE",
                            Title = "Switzerland"
                        },
                        new
                        {
                            Id = "760",
                            A2Code = "SY",
                            A3Code = "SYR",
                            Title = "Syrian Arab Republic"
                        },
                        new
                        {
                            Id = "158",
                            A2Code = "TW",
                            A3Code = "TWN",
                            Title = "Taiwan (Province of China)"
                        },
                        new
                        {
                            Id = "762",
                            A2Code = "TJ",
                            A3Code = "TJK",
                            Title = "Tajikistan"
                        },
                        new
                        {
                            Id = "834",
                            A2Code = "TZ",
                            A3Code = "TZA",
                            Title = "Tanzania, United Republic of"
                        },
                        new
                        {
                            Id = "764",
                            A2Code = "TH",
                            A3Code = "THA",
                            Title = "Thailand"
                        },
                        new
                        {
                            Id = "626",
                            A2Code = "TL",
                            A3Code = "TLS",
                            Title = "Timor-Leste"
                        },
                        new
                        {
                            Id = "768",
                            A2Code = "TG",
                            A3Code = "TGO",
                            Title = "Togo"
                        },
                        new
                        {
                            Id = "772",
                            A2Code = "TK",
                            A3Code = "TKL",
                            Title = "Tokelau"
                        },
                        new
                        {
                            Id = "776",
                            A2Code = "TO",
                            A3Code = "TON",
                            Title = "Tonga"
                        },
                        new
                        {
                            Id = "780",
                            A2Code = "TT",
                            A3Code = "TTO",
                            Title = "Trinidad and Tobago"
                        },
                        new
                        {
                            Id = "788",
                            A2Code = "TN",
                            A3Code = "TUN",
                            Title = "Tunisia"
                        },
                        new
                        {
                            Id = "792",
                            A2Code = "TR",
                            A3Code = "TUR",
                            Title = "Turkey"
                        },
                        new
                        {
                            Id = "795",
                            A2Code = "TM",
                            A3Code = "TKM",
                            Title = "Turkmenistan"
                        },
                        new
                        {
                            Id = "796",
                            A2Code = "TC",
                            A3Code = "TCA",
                            Title = "Turks and Caicos Islands (the)"
                        },
                        new
                        {
                            Id = "798",
                            A2Code = "TV",
                            A3Code = "TUV",
                            Title = "Tuvalu"
                        },
                        new
                        {
                            Id = "800",
                            A2Code = "UG",
                            A3Code = "UGA",
                            Title = "Uganda"
                        },
                        new
                        {
                            Id = "804",
                            A2Code = "UA",
                            A3Code = "UKR",
                            Title = "Ukraine"
                        },
                        new
                        {
                            Id = "784",
                            A2Code = "AE",
                            A3Code = "ARE",
                            Title = "United Arab Emirates (the)"
                        },
                        new
                        {
                            Id = "826",
                            A2Code = "GB",
                            A3Code = "GBR",
                            Title = "United Kingdom of Great Britain and Northern Ireland (the)"
                        },
                        new
                        {
                            Id = "581",
                            A2Code = "UM",
                            A3Code = "UMI",
                            Title = "United States Minor Outlying Islands (the)"
                        },
                        new
                        {
                            Id = "840",
                            A2Code = "US",
                            A3Code = "USA",
                            Title = "United States of America (the)"
                        },
                        new
                        {
                            Id = "858",
                            A2Code = "UY",
                            A3Code = "URY",
                            Title = "Uruguay"
                        },
                        new
                        {
                            Id = "860",
                            A2Code = "UZ",
                            A3Code = "UZB",
                            Title = "Uzbekistan"
                        },
                        new
                        {
                            Id = "548",
                            A2Code = "VU",
                            A3Code = "VUT",
                            Title = "Vanuatu"
                        },
                        new
                        {
                            Id = "862",
                            A2Code = "VE",
                            A3Code = "VEN",
                            Title = "Venezuela (Bolivarian Republic of)"
                        },
                        new
                        {
                            Id = "704",
                            A2Code = "VN",
                            A3Code = "VNM",
                            Title = "Viet Nam"
                        },
                        new
                        {
                            Id = "092",
                            A2Code = "VG",
                            A3Code = "VGB",
                            Title = "Virgin Islands (British)"
                        },
                        new
                        {
                            Id = "850",
                            A2Code = "VI",
                            A3Code = "VIR",
                            Title = "Virgin Islands (U.S.)"
                        },
                        new
                        {
                            Id = "876",
                            A2Code = "WF",
                            A3Code = "WLF",
                            Title = "Wallis and Futuna"
                        },
                        new
                        {
                            Id = "732",
                            A2Code = "EH",
                            A3Code = "ESH",
                            Title = "Western Sahara"
                        },
                        new
                        {
                            Id = "887",
                            A2Code = "YE",
                            A3Code = "YEM",
                            Title = "Yemen"
                        },
                        new
                        {
                            Id = "894",
                            A2Code = "ZM",
                            A3Code = "ZMB",
                            Title = "Zambia"
                        },
                        new
                        {
                            Id = "716",
                            A2Code = "ZW",
                            A3Code = "ZWE",
                            Title = "Zimbabwe"
                        },
                        new
                        {
                            Id = "248",
                            A2Code = "AX",
                            A3Code = "ALA",
                            Title = "Åland Islands"
                        });
                });

            modelBuilder.Entity("Topsis.Domain.Criterion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<short>("Order")
                        .HasColumnType("smallint");

                    b.Property<int?>("QuestionnaireId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionnaireId");

                    b.ToTable("WsCriteria");
                });

            modelBuilder.Entity("Topsis.Domain.JobCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("WsJobCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Academia/Researcher"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Private Sector/Industry"
                        },
                        new
                        {
                            Id = 3,
                            Title = "International Institution"
                        },
                        new
                        {
                            Id = 4,
                            Title = "National Government"
                        },
                        new
                        {
                            Id = 5,
                            Title = "Regional/Local Government"
                        },
                        new
                        {
                            Id = 6,
                            Title = "Policymaker"
                        },
                        new
                        {
                            Id = 7,
                            Title = "NGO"
                        },
                        new
                        {
                            Id = 8,
                            Title = "Press"
                        },
                        new
                        {
                            Id = 9,
                            Title = "Civil Society"
                        },
                        new
                        {
                            Id = 100,
                            Title = "Other"
                        });
                });

            modelBuilder.Entity("Topsis.Domain.Questionnaire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("DefaultCriterionWeight")
                        .HasColumnType("double");

                    b.Property<string>("_settings")
                        .HasColumnName("SettingsJson")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("WsQuestionnaires");
                });

            modelBuilder.Entity("Topsis.Domain.StakeholderAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AlternativeId")
                        .HasColumnType("int");

                    b.Property<int>("CriterionId")
                        .HasColumnType("int");

                    b.Property<double>("Value")
                        .HasColumnType("double");

                    b.Property<int>("VoteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlternativeId");

                    b.HasIndex("CriterionId");

                    b.HasIndex("VoteId");

                    b.ToTable("WsStakeholderAnswers");
                });

            modelBuilder.Entity("Topsis.Domain.StakeholderCriterionImportance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CriterionId")
                        .HasColumnType("int");

                    b.Property<int>("VoteId")
                        .HasColumnType("int");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CriterionId");

                    b.HasIndex("VoteId");

                    b.ToTable("WsStakeholderCriteriaImportance");
                });

            modelBuilder.Entity("Topsis.Domain.StakeholderVote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<int>("WorkspaceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("WorkspaceId")
                        .HasName("IX_STAKEHOLDERVOTE_WORKSPACEID");

                    b.ToTable("WsStakeholderVotes");
                });

            modelBuilder.Entity("Topsis.Domain.Workspace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<short>("CurrentStatus")
                        .HasColumnType("smallint");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(1024) CHARACTER SET utf8mb4")
                        .HasMaxLength(1024);

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<int?>("QuestionnaireId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4")
                        .HasMaxLength(255);

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.HasIndex("ParentId")
                        .IsUnique();

                    b.HasIndex("QuestionnaireId");

                    b.ToTable("WsWorkspaces");
                });

            modelBuilder.Entity("Topsis.Domain.WorkspaceReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<short>("Algorithm")
                        .HasColumnType("smallint");

                    b.Property<string>("Alternatives")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Criteria")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("VotesCount")
                        .HasColumnType("int");

                    b.Property<int>("WorkspaceId")
                        .HasColumnType("int");

                    b.Property<string>("_analysisResultJson")
                        .HasColumnName("AnalysisResultJson")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "Algorithm")
                        .IsUnique();

                    b.ToTable("WsWorkspacesReports");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Topsis.Application.Contracts.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Topsis.Application.Contracts.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Topsis.Application.Contracts.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Topsis.Application.Contracts.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Topsis.Application.Contracts.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Topsis.Application.Contracts.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Topsis.Application.Contracts.Identity.ApplicationUser", b =>
                {
                    b.HasOne("Topsis.Domain.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId");

                    b.HasOne("Topsis.Domain.JobCategory", "JobCategory")
                        .WithMany()
                        .HasForeignKey("JobCategoryId");

                    b.OwnsOne("Topsis.Domain.Contracts.ChangeTrack", "Created", b1 =>
                        {
                            b1.Property<string>("ApplicationUserId")
                                .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                            b1.Property<DateTime>("Time")
                                .HasColumnType("datetime(6)");

                            b1.Property<string>("UserId")
                                .HasColumnType("longtext CHARACTER SET utf8mb4");

                            b1.HasKey("ApplicationUserId");

                            b1.ToTable("AspNetUsers");

                            b1.WithOwner()
                                .HasForeignKey("ApplicationUserId");
                        });
                });

            modelBuilder.Entity("Topsis.Domain.Alternative", b =>
                {
                    b.HasOne("Topsis.Domain.Questionnaire", null)
                        .WithMany("Alternatives")
                        .HasForeignKey("QuestionnaireId");
                });

            modelBuilder.Entity("Topsis.Domain.Criterion", b =>
                {
                    b.HasOne("Topsis.Domain.Questionnaire", null)
                        .WithMany("Criteria")
                        .HasForeignKey("QuestionnaireId");
                });

            modelBuilder.Entity("Topsis.Domain.StakeholderAnswer", b =>
                {
                    b.HasOne("Topsis.Domain.Alternative", "Alternative")
                        .WithMany()
                        .HasForeignKey("AlternativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Topsis.Domain.Criterion", "Criterion")
                        .WithMany()
                        .HasForeignKey("CriterionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Topsis.Domain.StakeholderVote", "Vote")
                        .WithMany("Answers")
                        .HasForeignKey("VoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Topsis.Domain.StakeholderCriterionImportance", b =>
                {
                    b.HasOne("Topsis.Domain.Criterion", "Criterion")
                        .WithMany()
                        .HasForeignKey("CriterionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Topsis.Domain.StakeholderVote", "Vote")
                        .WithMany("CriteriaImportance")
                        .HasForeignKey("VoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Topsis.Domain.StakeholderVote", b =>
                {
                    b.HasOne("Topsis.Application.Contracts.Identity.ApplicationUser", null)
                        .WithMany("Votes")
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("Topsis.Domain.Workspace", "Workspace")
                        .WithMany("Votes")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Topsis.Domain.Workspace", b =>
                {
                    b.HasOne("Topsis.Domain.Workspace", "Parent")
                        .WithOne()
                        .HasForeignKey("Topsis.Domain.Workspace", "ParentId");

                    b.HasOne("Topsis.Domain.Questionnaire", "Questionnaire")
                        .WithMany()
                        .HasForeignKey("QuestionnaireId");
                });

            modelBuilder.Entity("Topsis.Domain.WorkspaceReport", b =>
                {
                    b.HasOne("Topsis.Domain.Workspace", "Workspace")
                        .WithMany("Reports")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
